import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Home/Banner'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home|Exo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
    </div>
  )
}
