import Head from "next/head";
import Banner from "../components/Responsible/Banner";

const responsible = () => {
     return (
       <>
         <Head>
           <title>Responsible|DMC</title>
           <meta name="description" content="Generated by create next app" />
           <link rel="icon" href="/favicon.ico" />
         </Head>
         <Banner />
       </>
     );
};

export default responsible;