import Head from "next/head";
import Banner from "../components/Responsible/Banner";
import Positive from "../components/Responsible/Positive";
import ResponsibleBody from "../components/Responsible/ResponsibleBody";

const responsible = () => {
     return (
       <>
         <Head>
           <title>Responsible|DMC</title>
           <meta name="description" content="Generated by create next app" />
           <link rel="icon" href="/favicon.ico" />
         </Head>
               <Banner />
               <Positive />
               <ResponsibleBody/>
       </>
     );
};

export default responsible;